### ISSUE TITLE
How I may to do what CTI-Toolbox works?

### ISSUE THREAD

**Issue by santi10** [johestephan/CTI-Toolbox#1]
HI,

I've cloned this git repositoty. I've created the file "iprep_conf.py" as README says but I don't know to work wiht CTI-Toolbox...do you have any idea about this, please?

Thanks

**Comment by johestephan** [comment]
I have uploaded an iprep_conf.py.CHANGEME file, it gives an overview on the configuration.
Then you need to add the api keys for the different sources, 

example:
xfexchange -> IBM XForce Exchange
otx.py -> Alienvault OTX
and so on

other tools work without an API key, like indifetch.py
sys.path.append("./")
import indifetch
Text = "109.234.106.8 is an IP address"
print indifetch.getIP(Text)

**Comment by santi10** [comment]
Hi Johestephan,

If I've understaned you fine, have I to run each scrpt?

Yo can see a sample, such as:
root@CS-01:/opt/CTI-Toolbox# python xfexchange.py -i 8.8.8.8
Traceback (most recent call last):
  File "xfexchange.py", line 310, in <module>
    print getip(options.ip)
  File "xfexchange.py", line 105, in getip
    return [str(data2), "Ups", "Ups", "ups"]
UnboundLocalError: local variable 'data2' referenced before assignment


Anyway I run vt.py or otx.py and these aren't working properly, when I run the script I don't give response as if the script not works...it seems odd

Thx!

**Comment by johestephan** [comment]
Well,

have you obtained the API keys from Xforce? (and OTX, VT)

If not, that causes the error. 

You can import each module. What are you trying to do?

**Comment by santi10** [comment]
Yes, I've obtained the API Keys and I've configured the file iprep_conf.py as you said me before. I run anything script and thes scripts aren't working.

**Comment by johestephan** [comment]
Send me a message to my email address (johe.stephan AT gmail.com) with your config, I will verify. For me it is working all day. <it is even in production as the backend of a portal and used by several people a day.
